/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: cvs/mig/Attic/lexxer.c,v 1.4 2001/12/31 23:41:46 roland Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 101
#define YY_END_OF_BUFFER 102
static yyconst short int yy_accept[520] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  102,  100,   98,   99,   95,   78,   79,   76,
       74,   73,   75,   77,   89,   71,   72,   83,   80,   84,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   85,   86,   81,
       88,   87,   82,   90,  100,  100,  100,   97,   97,   96,
       95,    0,    0,   94,   89,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   11,   88,   88,   88,
       88,   88,   19,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,

       90,    0,   91,    0,    0,   92,    0,    0,    0,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   12,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,    0,   93,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   31,   88,   88,   88,   28,   88,   88,   88,   88,
       18,   88,   88,   36,   88,   88,   88,   88,   20,   88,

       88,   13,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   24,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   25,   33,   40,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   32,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   42,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   34,   88,
       88,   88,   88,   46,    1,   88,   88,   88,   88,   88,
       27,   88,   88,   26,   88,   88,   88,   88,   88,   88,

       39,   88,    2,   88,   88,   88,   88,   88,    8,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,    9,   88,   88,   37,   88,   41,
       88,   88,   88,    7,   88,   88,   88,    3,   15,   88,
       88,   88,   88,   88,   88,   88,    6,   88,   88,   45,
       88,   35,   88,   30,   88,   43,   10,   88,   88,   44,
       88,   88,   88,   88,   17,   16,   22,   38,   88,   88,
       47,   14,   23,   88,   88,   88,   29,   88,   21,   88,
       88,   88,   88,    5,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,    4,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   49,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   55,   54,   88,   88,   88,   88,   88,   88,   57,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   58,   88,   50,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   59,   88,   61,   88,   88,   88,
       56,   62,   88,   63,   88,   66,   88,   68,   88,   51,
       52,   53,   88,   88,   88,   88,   88,   88,   88,   88,

       88,   88,   70,   88,   88,   88,   88,   60,   88,   67,
       88,   48,   88,   88,   88,   64,   65,   69,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    7,    1,    1,    1,    8,
        9,   10,   11,   12,   13,    7,   14,   15,   16,   17,
       18,   19,   15,   20,   15,   21,   15,   22,   23,   24,
       25,   26,    1,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   36,
       52,    1,   53,   54,   55,    1,   56,   57,   58,   59,

       60,   32,   61,   62,   63,   36,   64,   65,   66,   67,
       68,   69,   43,   70,   71,   72,   73,   74,   49,   50,
       75,   36,    1,   76,    1,   77,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[78] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    3,    3,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1
    } ;

static yyconst short int yy_base[529] =
    {   0,
        0,    3,    9,  989,   86,  163,   97,  101,  111,  124,
      115,  129,  994,  996,  996,  996,  132,  996,  996,  996,
      996,  996,  996,  996,  139,  996,  996,  996,  996,  996,
       76,    0,  135,   62,  100,  131,  152,  152,  134,  143,
      162,  152,  169,  210,  126,  189,  172,  996,  996,  996,
      150,  996,  996,    0,  988,  966,  986,  996,  996,  996,
      246,  273,  282,  302,  293,    0,  181,  185,  171,  163,
      197,  198,  260,  202,  186,  202,  283,  287,  211,  961,
      282,  284,    0,  286,  211,  285,  289,  293,  290,  294,
      301,  306,  297,  298,  316,  303,  308,  315,  317,  315,

        0,  984,  996,  962,  982,  996,  377,  381,  981,  332,
      309,  317,  338,  339,  338,  351,  345,  359,  361,  360,
      356,  360,  364,  365,  368,  951,  368,  372,  384,  366,
      367,  385,  385,  384,  368,  392,  379,  378,  392,  395,
      402,  399,  402,  393,  412,  413,  413,  412,  979,  996,
      394,  413,  412,  431,  419,  422,  429,  426,  430,  429,
      432,  431,  441,  438,  434,  448,  928,  445,  457,  459,
      430,  451,  459,  468,  474,  456,  478,  469,  476,  481,
      475,    0,  477,  489,  469,    0,  481,  485,  482,  480,
        0,  492,  498,    0,  484,  497,  493,  489,    0,  500,

      499,    0,  506,  515,  515,  516,  943,  511,  938,  532,
      518,  538,  525,  537,    0,  526,  527,  540,  534,  533,
      544,  535,  527,  536,  539,  541,  538,  542,  534,  547,
      547,  541,  560,  577,  578,  574,    0,    0,    0,  577,
      575,  935,  574,  583,  586,  575,  585,  584,  582,  585,
      584,  600,  601,  628,  596,  587,  599,    0,  597,  603,
      602,  603,  623,  623,  621,  630,  640,    0,  628,  636,
      637,  647,  634,  946,  640,  641,  645,  649,    0,  646,
      636,  641,  648,    0,    0,  651,  663,  651,  652,  657,
        0,  661,  682,    0,  673,  946,  685,  671,  673,  689,

        0,  685,    0,  694,  684,  699,  922,  691,    0,  692,
      695,  701,  705,  692,  698,  698,  704,  715,  706,  703,
      707,  713,  712,  722,    0,  716,  726,    0,  727,    0,
      724,  729,  930,    0,  749,  749,  748,    0,    0,  740,
      718,  739,  943,  758,  743,  745,    0,  746,  924,    0,
      759,    0,  763,    0,  922,    0,    0,  767,  754,    0,
      922,  766,  771,  769,    0,    0,    0,    0,  764,  929,
        0,    0,    0,  920,  776,  763,    0,  938,    0,  766,
      783,  913,  776,    0,  809,  790,  244,  799,  927,   96,
      925,  934,  918,  923,    0,  916,  920,  914,  932,  916,

      911,  919,  907,  192,  927,  909,  907,    0,  913,  919,
      905,  897,  916,  915,  914,  893,  897,  904,  906,  894,
      908,    0,    0,  883,  904,  881,  880,  895,  878,    0,
      892,  887,  903,  884,  897,  882,   97,  885,  815,  892,
      877,  883,  891,  877,  889,  888,  887,  873,  889,  884,
      883,  858,  883,    0,  871,  855,  869,  879,  867,  864,
      866,  875,  863,  873,  855,  870,  845,  869,  867,  867,
      856,  855,  851,  834,    0,  815,    0,  838,  840,  833,
        0,  794,  812,  790,  807,    0,  806,  781,  784,    0,
        0,    0,  786,  776,  781,  776,  733,  696,  701,  599,

      588,  416,    0,  392,  331,  336,  267,    0,  249,    0,
      184,    0,  114,  112,   93,    0,    0,    0,  996,  866,
      870,  874,    4,  876,  880,  884,  888,  892
    } ;

static yyconst short int yy_def[529] =
    {   0,
      520,  520,  519,    3,  521,  521,  520,  520,  520,  520,
      522,  522,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  519,  519,  519,
      523,  519,  519,  524,  525,  526,  527,  519,  519,  519,
      519,  519,  519,  519,  519,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,

      524,  525,  519,  526,  527,  519,  519,  519,  528,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  528,  519,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,

      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,

      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,

      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,

      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,    0,  519,
      519,  519,  519,  519,  519,  519,  519,  519
    } ;

static yyconst short int yy_nxt[1074] =
    {   0,
      519,   15,   16,   15,   15,   16,   15,   66,   17,   14,
       15,   16,   15,   14,   14,   14,   18,   19,   20,   21,
       22,   23,   24,   25,   25,   25,   25,   25,   25,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   32,   32,   37,   32,   38,   32,   39,   40,   41,
       42,   32,   43,   44,   45,   46,   32,   47,   32,   32,
       48,   49,   50,   32,   31,   32,   33,   34,   35,   32,
       32,   37,   38,   32,   51,   40,   41,   42,   43,   44,
       45,   46,   32,   32,   52,   53,   14,   15,   16,   15,
       14,   14,   73,   14,   14,   14,   14,   14,   15,   16,

       15,   55,   15,   16,   15,   55,   17,   14,   14,   14,
       14,   14,   15,   16,   15,   57,   59,   60,   59,   67,
       56,   73,  402,  518,   56,   15,   16,   15,   57,   17,
       59,   60,   59,   62,   61,   63,  403,   14,   14,   14,
      446,  447,  517,   74,  516,   67,   64,   64,   64,   64,
       64,   64,   64,   65,   65,   65,   65,   65,   65,   65,
       80,   14,   14,   14,   15,   16,   15,   14,   17,   74,
       14,   14,   14,   14,   14,   68,   96,   75,   81,   69,
       70,   71,   79,   82,   14,   14,   14,   14,   14,   72,
       76,   77,   85,   83,   81,   86,   78,   87,  100,   88,

       96,  112,   68,   75,   81,   69,   70,   71,   84,   89,
       82,   79,  515,  113,   14,   14,   14,   76,   77,   85,
       81,   86,   78,   97,  110,  119,   87,  100,   88,  416,
      112,  111,   98,   99,   84,  417,   89,  113,   14,   14,
       90,  114,  115,  120,   91,  118,   92,   62,  131,   63,
      110,   97,  119,   93,  125,   94,   95,  111,   98,   99,
       64,   64,   64,   64,   64,   64,   64,  114,  115,   90,
      120,  118,   91,   92,   62,  131,   62,  514,  396,   93,
      125,   94,   95,   62,  397,   63,  116,  107,  107,  107,
      107,  107,  107,  107,  398,  513,   64,   64,   64,   64,

       64,   64,   64,  108,  117,  108,  109,   65,   65,   65,
       65,   65,   65,   65,  127,  116,   64,   64,   64,   64,
       64,   64,   64,  121,  123,  132,  124,  141,  122,  128,
      117,  130,  129,  133,  134,  135,  137,  138,  136,  139,
      140,  142,  127,  143,  144,  146,  145,  147,  152,  148,
      121,  123,  132,  124,  122,  128,  141,  130,  151,  133,
      153,  134,  137,  138,  136,  512,  139,  142,  140,  155,
      511,  144,  143,  145,  146,  152,  147,  148,  108,  154,
      108,  109,  108,  156,  108,  109,  153,  151,  157,  160,
      158,  107,  107,  107,  107,  107,  107,  107,  155,  159,

      161,  170,  162,  163,  164,  165,  154,  166,  168,  156,
      171,  172,  169,  174,  177,  157,  158,  173,  160,  175,
      178,  176,  510,  186,  179,  180,  159,  161,  162,  163,
      170,  164,  165,  181,  166,  168,  182,  172,  169,  171,
      177,  173,  174,  183,  191,  184,  185,  175,  176,  178,
      179,  180,  186,  187,  188,  509,  189,  190,  192,  193,
      181,  194,  195,  182,  211,  196,  197,  203,  191,  198,
      183,  184,  185,  199,  200,  201,  202,  204,  206,  205,
      187,  188,  189,  190,  192,  193,  208,  209,  195,  210,
      194,  196,  211,  197,  212,  198,  203,  213,  214,  199,

      200,  201,  202,  215,  204,  205,  216,  206,  217,  218,
      219,  220,  221,  208,  223,  222,  209,  224,  210,  225,
      212,  226,  227,  228,  213,  229,  230,  214,  231,  232,
      216,  233,  215,  234,  236,  235,  218,  217,  219,  221,
      220,  223,  222,  225,  237,  238,  224,  239,  226,  227,
      228,  229,  240,  241,  230,  232,  243,  231,  245,  233,
      234,  235,  236,  246,  247,  248,  249,  250,  263,  252,
      237,  251,  238,  253,  255,  239,  254,  257,  256,  240,
      241,  258,  243,  259,  260,  262,  264,  245,  261,  246,
      265,  266,  248,  247,  250,  249,  263,  251,  252,  267,

      253,  257,  254,  255,  256,  268,  269,  258,  275,  259,
      260,  262,  261,  264,  270,  266,  265,  271,  508,  272,
      278,  273,  276,  277,  279,  282,  267,  280,  281,  283,
      284,  285,  291,  296,  268,  269,  275,  289,  507,  290,
      292,  270,  293,  295,  271,  272,  278,  273,  294,  276,
      277,  279,  282,  280,  281,  283,  286,  287,  291,  284,
      285,  297,  296,  298,  289,  290,  299,  292,  293,  288,
      295,  300,  301,  302,  294,  303,  304,  305,  306,  313,
      308,  309,  310,  311,  314,  286,  287,  312,  297,  315,
      298,  316,  299,  317,  318,  319,  288,  320,  300,  302,

      301,  321,  303,  304,  306,  313,  305,  308,  309,  310,
      314,  311,  322,  323,  312,  325,  315,  326,  316,  328,
      318,  319,  317,  327,  320,  329,  330,  331,  321,  332,
      334,  506,  335,  336,  337,  338,  505,  339,  340,  341,
      323,  322,  342,  326,  325,  343,  344,  327,  328,  345,
      346,  347,  329,  331,  330,  348,  349,  334,  332,  335,
      336,  350,  337,  339,  338,  340,  341,  351,  360,  342,
      352,  353,  354,  344,  343,  345,  346,  356,  347,  357,
      504,  348,  358,  359,  349,  361,  363,  350,  364,  368,
      365,  366,  360,  369,  351,  371,  352,  353,  354,  372,

      374,  375,  381,  376,  503,  380,  356,  377,  357,  359,
      358,  361,  383,  384,  364,  363,  365,  366,  368,  386,
      395,  502,  369,  501,  371,  372,  500,  499,  374,  381,
      375,  376,  399,  377,  380,  498,  387,  388,  383,  400,
      497,  496,  384,  389,  495,  386,  494,  390,  493,  395,
      391,  492,  392,  393,  449,  394,  491,  490,  450,  451,
      478,  489,  479,  488,  480,  481,   14,   14,   14,   14,
       54,   54,   54,   54,   58,   58,   58,   58,  101,  101,
      102,  487,  102,  102,  104,  486,  104,  104,  105,  485,
      105,  105,  149,  149,  149,  149,  484,  483,  482,  477,

      476,  475,  474,  473,  472,  471,  470,  469,  468,  467,
      466,  465,  464,  463,  462,  461,  460,  459,  458,  457,
      456,  455,  454,  453,  452,  448,  445,  444,  443,  442,
      441,  440,  439,  438,  437,  436,  435,  434,  433,  432,
      431,  430,  429,  428,  427,  426,  425,  424,  423,  422,
      421,  420,  419,  418,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  406,  405,  404,  401,  385,  382,  379,
      378,  373,  370,  367,  362,  355,  333,  324,  307,  274,
      244,  242,  207,  150,  167,  150,  106,  103,  103,  126,
      106,  103,  103,  519,   17,   13,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519
    } ;

static yyconst short int yy_chk[1074] =
    {   0,
        0,    1,    1,    1,    2,    2,    2,  523,    2,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    5,    5,    5,    5,
        5,    5,   34,    5,    5,    5,    5,    5,    7,    7,

        7,    7,    8,    8,    8,    8,    8,    5,    5,    5,
        5,    5,    9,    9,    9,    9,   11,   11,   11,   31,
        7,   34,  390,  515,    8,   10,   10,   10,   10,   10,
       12,   12,   12,   17,   12,   17,  390,    5,    5,    5,
      437,  437,  514,   35,  513,   31,   17,   17,   17,   17,
       17,   17,   17,   25,   25,   25,   25,   25,   25,   25,
       39,    5,    5,    6,    6,    6,    6,    6,    6,   35,
        6,    6,    6,    6,    6,   33,   45,   36,   39,   33,
       33,   33,   38,   40,    6,    6,    6,    6,    6,   33,
       37,   37,   42,   41,   51,   42,   37,   43,   47,   43,

       45,   69,   33,   36,   39,   33,   33,   33,   41,   43,
       40,   38,  511,   70,    6,    6,    6,   37,   37,   42,
       51,   42,   37,   46,   67,   75,   43,   47,   43,  404,
       69,   68,   46,   46,   41,  404,   43,   70,    6,    6,
       44,   71,   72,   76,   44,   74,   44,   61,   85,   61,
       67,   46,   75,   44,   79,   44,   44,   68,   46,   46,
       61,   61,   61,   61,   61,   61,   61,   71,   72,   44,
       76,   74,   44,   44,   62,   85,   62,  509,  387,   44,
       79,   44,   44,   63,  387,   63,   73,   62,   62,   62,
       62,   62,   62,   62,  387,  507,   63,   63,   63,   63,

       63,   63,   63,   64,   73,   64,   64,   65,   65,   65,
       65,   65,   65,   65,   81,   73,   64,   64,   64,   64,
       64,   64,   64,   77,   78,   86,   78,   93,   77,   82,
       73,   84,   82,   87,   88,   88,   89,   90,   88,   91,
       92,   94,   81,   95,   96,   98,   97,   99,  111,  100,
       77,   78,   86,   78,   77,   82,   93,   84,  110,   87,
      112,   88,   89,   90,   88,  506,   91,   94,   92,  114,
      505,   96,   95,   97,   98,  111,   99,  100,  107,  113,
      107,  107,  108,  115,  108,  108,  112,  110,  116,  119,
      117,  107,  107,  107,  107,  107,  107,  107,  114,  118,

      120,  128,  121,  122,  123,  124,  113,  125,  127,  115,
      129,  130,  127,  132,  135,  116,  117,  131,  119,  133,
      136,  134,  504,  144,  137,  138,  118,  120,  121,  122,
      128,  123,  124,  139,  125,  127,  140,  130,  127,  129,
      135,  131,  132,  141,  151,  142,  143,  133,  134,  136,
      137,  138,  144,  145,  146,  502,  147,  148,  152,  153,
      139,  154,  155,  140,  171,  156,  157,  163,  151,  158,
      141,  142,  143,  159,  160,  161,  162,  164,  166,  165,
      145,  146,  147,  148,  152,  153,  168,  169,  155,  170,
      154,  156,  171,  157,  172,  158,  163,  173,  174,  159,

      160,  161,  162,  175,  164,  165,  176,  166,  177,  178,
      179,  180,  181,  168,  183,  181,  169,  184,  170,  185,
      172,  187,  188,  189,  173,  190,  192,  174,  193,  195,
      176,  196,  175,  197,  200,  198,  178,  177,  179,  181,
      180,  183,  181,  185,  201,  203,  184,  204,  187,  188,
      189,  190,  205,  206,  192,  195,  208,  193,  210,  196,
      197,  198,  200,  211,  212,  213,  214,  216,  229,  218,
      201,  217,  203,  219,  221,  204,  220,  223,  222,  205,
      206,  224,  208,  225,  226,  228,  230,  210,  227,  211,
      231,  232,  213,  212,  216,  214,  229,  217,  218,  233,

      219,  223,  220,  221,  222,  234,  235,  224,  243,  225,
      226,  228,  227,  230,  236,  232,  231,  240,  501,  241,
      246,  241,  244,  245,  247,  250,  233,  248,  249,  251,
      252,  253,  256,  262,  234,  235,  243,  255,  500,  255,
      257,  236,  259,  261,  240,  241,  246,  241,  260,  244,
      245,  247,  250,  248,  249,  251,  254,  254,  256,  252,
      253,  263,  262,  264,  255,  255,  265,  257,  259,  254,
      261,  266,  267,  269,  260,  270,  271,  272,  273,  281,
      275,  276,  277,  278,  282,  254,  254,  280,  263,  283,
      264,  286,  265,  287,  288,  289,  254,  290,  266,  269,

      267,  292,  270,  271,  273,  281,  272,  275,  276,  277,
      282,  278,  293,  295,  280,  297,  283,  298,  286,  300,
      288,  289,  287,  299,  290,  302,  304,  305,  292,  306,
      308,  499,  310,  311,  312,  313,  498,  314,  315,  316,
      295,  293,  317,  298,  297,  318,  319,  299,  300,  320,
      321,  322,  302,  305,  304,  323,  324,  308,  306,  310,
      311,  326,  312,  314,  313,  315,  316,  327,  341,  317,
      329,  331,  332,  319,  318,  320,  321,  335,  322,  336,
      497,  323,  337,  340,  324,  342,  344,  326,  345,  351,
      346,  348,  341,  353,  327,  358,  329,  331,  332,  359,

      362,  363,  376,  364,  496,  375,  335,  369,  336,  340,
      337,  342,  380,  381,  345,  344,  346,  348,  351,  383,
      386,  495,  353,  494,  358,  359,  493,  489,  362,  376,
      363,  364,  388,  369,  375,  488,  385,  385,  380,  388,
      487,  485,  381,  385,  484,  383,  483,  385,  482,  386,
      385,  480,  385,  385,  439,  385,  479,  478,  439,  439,
      467,  476,  467,  474,  467,  467,  520,  520,  520,  520,
      521,  521,  521,  521,  522,  522,  522,  522,  524,  524,
      525,  473,  525,  525,  526,  472,  526,  526,  527,  471,
      527,  527,  528,  528,  528,  528,  470,  469,  468,  466,

      465,  464,  463,  462,  461,  460,  459,  458,  457,  456,
      455,  453,  452,  451,  450,  449,  448,  447,  446,  445,
      444,  443,  442,  441,  440,  438,  436,  435,  434,  433,
      432,  431,  429,  428,  427,  426,  425,  424,  421,  420,
      419,  418,  417,  416,  415,  414,  413,  412,  411,  410,
      409,  407,  406,  405,  403,  402,  401,  400,  399,  398,
      397,  396,  394,  393,  392,  391,  389,  382,  378,  374,
      370,  361,  355,  349,  343,  333,  307,  296,  274,  242,
      209,  207,  167,  149,  126,  109,  105,  104,  102,   80,
       57,   56,   55,   13,    4,  519,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../../mig/lexxer.l"
#define INITIAL 0
#line 15 "../../mig/lexxer.l"
/*
 * Mach Operating System
 * Copyright (c) 1991,1990 Carnegie Mellon University
 * All Rights Reserved.
 *
 * Permission to use, copy, modify and distribute this software and its
 * documentation is hereby granted, provided that both the copyright
 * notice and this permission notice appear in all copies of the
 * software, derivative works or modified versions, and any portions
 * thereof, and that both notices appear in supporting documentation.
 *
 * CARNEGIE MELLON ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS"
 * CONDITION.  CARNEGIE MELLON DISCLAIMS ANY LIABILITY OF ANY KIND FOR
 * ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
 *
 * Carnegie Mellon requests users of this software to return to
 *
 *  Software Distribution Coordinator  or  Software.Distribution@CS.CMU.EDU
 *  School of Computer Science
 *  Carnegie Mellon University
 *  Pittsburgh PA 15213-3890
 *
 * any improvements or extensions that they make and grant Carnegie Mellon
 * the rights to redistribute these changes.
 */

#include <string.h>

#include "mig_string.h"
#include "type.h"
#include "statement.h"
#include "global.h"
#include "parser.h"
#include "lexxer.h"
#include "cpu.h"

#define	stringize(x)	#x

#ifdef	LDEBUG
#define RETURN(sym)							\
{									\
    printf("yylex: returning '%s' (%d)\n", #sym, (sym));		\
    return (sym);							\
}
#else	/* LDEBUG */
#define RETURN(sym)	return (sym)
#endif	/* LDEBUG */

#define	TPRETURN(intype, outtype, tsize)				\
{									\
    yylval.symtype.innumber = (intype);					\
    yylval.symtype.instr = stringize(intype);				\
    yylval.symtype.outnumber = (outtype);				\
    yylval.symtype.outstr = stringize(outtype);				\
    yylval.symtype.size = (tsize);					\
    RETURN(sySymbolicType);						\
}

#define	TRETURN(type, tsize)	TPRETURN(type,type,tsize)

#define	FRETURN(val)							\
{									\
    yylval.flag = (val);						\
    RETURN(syIPCFlag);							\
}

extern YYSTYPE yylval;		/* added by rm */

int lineno;
char *inname;

#ifdef	YY_START
static int oldYYBegin;
#define SAVE_BEGIN oldYYBegin = YY_START
#define RSTR_BEGIN BEGIN oldYYBegin
#else
static struct yysvf *oldYYBegin;
#define SAVE_BEGIN oldYYBegin = yybgin
#define RSTR_BEGIN yybgin = oldYYBegin;
#endif

static void doSharp(const char *body); /* process body of # directives */
#define Normal 1
#define String 2
#define FileName 3
#define QString 4
#define SkipToEOL 5

#line 863 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 101 "../../mig/lexxer.l"


#line 1020 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 520 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 996 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 103 "../../mig/lexxer.l"
RETURN(syRoutine);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 104 "../../mig/lexxer.l"
RETURN(syFunction);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 105 "../../mig/lexxer.l"
RETURN(syProcedure);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 106 "../../mig/lexxer.l"
RETURN(sySimpleProcedure);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 107 "../../mig/lexxer.l"
RETURN(sySimpleRoutine);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 108 "../../mig/lexxer.l"
RETURN(sySubsystem);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 109 "../../mig/lexxer.l"
RETURN(syMsgOption);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 110 "../../mig/lexxer.l"
RETURN(syMsgSeqno);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 111 "../../mig/lexxer.l"
RETURN(syWaitTime);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 112 "../../mig/lexxer.l"
RETURN(syNoWaitTime);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 113 "../../mig/lexxer.l"
RETURN(syIn);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 114 "../../mig/lexxer.l"
RETURN(syOut);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "../../mig/lexxer.l"
RETURN(syInOut);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 116 "../../mig/lexxer.l"
RETURN(syRequestPort);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 117 "../../mig/lexxer.l"
RETURN(syReplyPort);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 118 "../../mig/lexxer.l"
RETURN(syUReplyPort);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 119 "../../mig/lexxer.l"
RETURN(sySReplyPort);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 120 "../../mig/lexxer.l"
RETURN(syArray);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 121 "../../mig/lexxer.l"
RETURN(syOf);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 122 "../../mig/lexxer.l"
RETURN(syErrorProc);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 123 "../../mig/lexxer.l"
RETURN(syServerPrefix);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 124 "../../mig/lexxer.l"
RETURN(syUserPrefix);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 125 "../../mig/lexxer.l"
RETURN(syServerDemux);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 126 "../../mig/lexxer.l"
RETURN(syRCSId);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 127 "../../mig/lexxer.l"
RETURN(syImport);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 128 "../../mig/lexxer.l"
RETURN(syUImport);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 129 "../../mig/lexxer.l"
RETURN(sySImport);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 130 "../../mig/lexxer.l"
RETURN(syType);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 131 "../../mig/lexxer.l"
RETURN(syKernelServer);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 132 "../../mig/lexxer.l"
RETURN(syKernelUser);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 133 "../../mig/lexxer.l"
RETURN(sySkip);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 134 "../../mig/lexxer.l"
RETURN(syStruct);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 135 "../../mig/lexxer.l"
RETURN(syInTran);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 136 "../../mig/lexxer.l"
RETURN(syOutTran);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 137 "../../mig/lexxer.l"
RETURN(syDestructor);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 138 "../../mig/lexxer.l"
RETURN(syCType);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 139 "../../mig/lexxer.l"
RETURN(syCUserType);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 140 "../../mig/lexxer.l"
RETURN(syCServerType);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 141 "../../mig/lexxer.l"
RETURN(syCString);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 143 "../../mig/lexxer.l"
FRETURN(flLong);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 144 "../../mig/lexxer.l"
FRETURN(flNotLong);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 145 "../../mig/lexxer.l"
FRETURN(flDealloc);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 146 "../../mig/lexxer.l"
FRETURN(flNotDealloc);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 147 "../../mig/lexxer.l"
FRETURN(flServerCopy);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 148 "../../mig/lexxer.l"
FRETURN(flCountInOut);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 149 "../../mig/lexxer.l"
FRETURN(flNone);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 151 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_POLYMORPHIC,word_size_in_bits);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 153 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_UNSTRUCTURED,0);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 154 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_BIT,1);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 155 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_BOOLEAN,32);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 156 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_INTEGER_16,16);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 157 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_INTEGER_32,32);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 158 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_INTEGER_64,64);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 159 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_CHAR,8);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 160 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_BYTE,8);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 161 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_INTEGER_8,8);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 162 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_REAL,0);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 163 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_STRING,0);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 164 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_STRING_C,0);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 166 "../../mig/lexxer.l"
TPRETURN(MACH_MSG_TYPE_MOVE_RECEIVE,MACH_MSG_TYPE_PORT_RECEIVE,word_size_in_bits);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 167 "../../mig/lexxer.l"
TPRETURN(MACH_MSG_TYPE_COPY_SEND,MACH_MSG_TYPE_PORT_SEND,word_size_in_bits);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 168 "../../mig/lexxer.l"
TPRETURN(MACH_MSG_TYPE_MAKE_SEND,MACH_MSG_TYPE_PORT_SEND,word_size_in_bits);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 169 "../../mig/lexxer.l"
TPRETURN(MACH_MSG_TYPE_MOVE_SEND,MACH_MSG_TYPE_PORT_SEND,word_size_in_bits);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 170 "../../mig/lexxer.l"
TPRETURN(MACH_MSG_TYPE_MAKE_SEND_ONCE,MACH_MSG_TYPE_PORT_SEND_ONCE,word_size_in_bits);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 171 "../../mig/lexxer.l"
TPRETURN(MACH_MSG_TYPE_MOVE_SEND_ONCE,MACH_MSG_TYPE_PORT_SEND_ONCE,word_size_in_bits);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 173 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_PORT_NAME,word_size_in_bits);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 174 "../../mig/lexxer.l"
TPRETURN(MACH_MSG_TYPE_POLYMORPHIC,MACH_MSG_TYPE_PORT_RECEIVE,word_size_in_bits);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 175 "../../mig/lexxer.l"
TPRETURN(MACH_MSG_TYPE_POLYMORPHIC,MACH_MSG_TYPE_PORT_SEND,word_size_in_bits);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 176 "../../mig/lexxer.l"
TPRETURN(MACH_MSG_TYPE_POLYMORPHIC,MACH_MSG_TYPE_PORT_SEND_ONCE,word_size_in_bits);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 177 "../../mig/lexxer.l"
TRETURN(MACH_MSG_TYPE_POLYMORPHIC,0);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 179 "../../mig/lexxer.l"
RETURN(syColon);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 180 "../../mig/lexxer.l"
RETURN(sySemi);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 181 "../../mig/lexxer.l"
RETURN(syComma);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 182 "../../mig/lexxer.l"
RETURN(syPlus);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 183 "../../mig/lexxer.l"
RETURN(syMinus);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 184 "../../mig/lexxer.l"
RETURN(syStar);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 185 "../../mig/lexxer.l"
RETURN(syDiv);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 186 "../../mig/lexxer.l"
RETURN(syLParen);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 187 "../../mig/lexxer.l"
RETURN(syRParen);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 188 "../../mig/lexxer.l"
RETURN(syEqual);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 189 "../../mig/lexxer.l"
RETURN(syCaret);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 190 "../../mig/lexxer.l"
RETURN(syTilde);
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 191 "../../mig/lexxer.l"
RETURN(syLAngle);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 192 "../../mig/lexxer.l"
RETURN(syRAngle);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 193 "../../mig/lexxer.l"
RETURN(syLBrack);
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 194 "../../mig/lexxer.l"
RETURN(syRBrack);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 195 "../../mig/lexxer.l"
RETURN(syBar);
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 197 "../../mig/lexxer.l"
{ yylval.identifier = strmake(yytext);
			  RETURN(syIdentifier); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 199 "../../mig/lexxer.l"
{ yylval.number = atoi(yytext); RETURN(syNumber); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 201 "../../mig/lexxer.l"
{ yylval.string = strmake(yytext);
			  BEGIN Normal; RETURN(syString); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 203 "../../mig/lexxer.l"
{ yylval.string = strmake(yytext);
			  BEGIN Normal; RETURN(syFileName); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 205 "../../mig/lexxer.l"
{ yylval.string = strmake(yytext);
			  BEGIN Normal; RETURN(syQString); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 208 "../../mig/lexxer.l"
{ doSharp(yytext+1);
					  SAVE_BEGIN;
					  BEGIN SkipToEOL; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 211 "../../mig/lexxer.l"
{ doSharp(yytext+1);
					  SAVE_BEGIN;
					  BEGIN SkipToEOL; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 214 "../../mig/lexxer.l"
{ yyerror("illegal # directive");
					  SAVE_BEGIN;
					  BEGIN SkipToEOL; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 218 "../../mig/lexxer.l"
RSTR_BEGIN;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 219 "../../mig/lexxer.l"
;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 221 "../../mig/lexxer.l"
;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 222 "../../mig/lexxer.l"
{ lineno++; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 223 "../../mig/lexxer.l"
{ BEGIN Normal; RETURN(syError); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 225 "../../mig/lexxer.l"
ECHO;
	YY_BREAK
#line 1619 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(Normal):
case YY_STATE_EOF(String):
case YY_STATE_EOF(FileName):
case YY_STATE_EOF(QString):
case YY_STATE_EOF(SkipToEOL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 520 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 520 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 519);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 225 "../../mig/lexxer.l"


extern void
LookNormal(void)
{
    if (inname == 0)
    {
	inname = strmake("(unknown)");
	lineno = 0;
    }

    BEGIN Normal;
}

extern void
LookString(void)
{
    BEGIN String;
}

extern void
LookQString(void)
{
    BEGIN QString;
}

extern void
LookFileName(void)
{
    BEGIN FileName;
}

static void
doSharp(const char *body)
{
    register const char *startName;

    lineno = atoi(body);
    startName = strchr(body, '"');
    if (startName != NULL)
    {
	*strrchr(body, '"') = '\0';
	strfree(inname);
	inname = strmake(startName+1);
    }
}
